# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies. 

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('../data/imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [3]:
# Number of rows?
# Number of columns?
imdb.shape

(1000, 16)

In [4]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [5]:
# Use describe() to summarize the descriptive statistics of *all* columns
imdb.describe(include='all')

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
count,1000,1000,1000,899,1000,1000,1000.000000,1000,843.000000,1000,1000,1000,1000,1000,1.000000e+03,831
unique,1000,999,100,16,140,202,NaN,1000,NaN,548,660,841,891,939,NaN,823
top,https://m.media-amazon.com/images/M/MV5BMDFkYT...,Drishyam,2014,U,100 min,Drama,NaN,Two imprisoned men bond over a number of years...,NaN,Alfred Hitchcock,Tom Hanks,Emma Watson,Rupert Grint,Michael Caine,NaN,"4,360,000"
freq,1,2,32,234,23,85,NaN,1,NaN,14,12,7,5,4,NaN,5
mean,NaN,NaN,NaN,NaN,NaN,NaN,7.949300,NaN,77.971530,NaN,NaN,NaN,NaN,NaN,2.736929e+05,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,0.275491,NaN,12.376099,NaN,NaN,NaN,NaN,NaN,3.273727e+05,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,7.600000,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,2.508800e+04,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.700000,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,5.552625e+04,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,7.900000,NaN,79.000000,NaN,NaN,NaN,NaN,NaN,1.385485e+05,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,8.100000,NaN,87.000000,NaN,NaN,NaN,NaN,NaN,3.741612e+05,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,9.300000,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,2.343110e+06,NaN

In [6]:
# List all the column names: 
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [7]:
# Display top 10 movies's title, released year and IMDB rating.
imdb.head(10).iloc[:,[1,2,6]]

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [8]:
# Display moviess ranked 11-20. 
# Show their title, released year and IMDB rating.
#imdb.iloc[10:20,[1,2,6]]
imdb.loc[10:19,['Series_Title','Released_Year','IMDB_Rating']]

,Series_Title,Released_Year,IMDB_Rating
10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
11,Forrest Gump,1994,8.8
12,"Il buono, il brutto, il cattivo",1966,8.8
13,The Lord of the Rings: The Two Towers,2002,8.7
14,The Matrix,1999,8.7
15,Goodfellas,1990,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
17,One Flew Over the Cuckoo's Nest,1975,8.7
18,Hamilton,2020,8.6
19,Gisaengchung,2019,8.6

In [9]:
# Select all movies directed by Quentin Tarantino.
# Show their title, released year, IMDB rating, and gross.
imdb[imdb.Director=='Quentin Tarantino'][['Series_Title','Released_Year','IMDB_Rating','Gross']]

                         Series_Title Released_Year  IMDB_Rating        Gross
6                        Pulp Fiction          1994          8.9  107,928,762
62                   Django Unchained          2012          8.4  162,805,434
93               Inglourious Basterds          2009          8.3  120,540,719
103                    Reservoir Dogs          1992          8.3    2,832,029
241                 Kill Bill: Vol. 1          2003          8.1   70,099,045
369                 Kill Bill: Vol. 2          2004          8.0   66,208,183
584                 The Hateful Eight          2015          7.8   54,117,416
879  Once Upon a Time... in Hollywood          2019          7.6  142,502,728

In [10]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.

imdb[(imdb.Certificate=='R') & (imdb.IMDB_Rating>=8.5)][['Series_Title','Released_Year','Certificate','IMDB_Rating']]

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [11]:
# How many unique values are there in the column "Released_Year"? 
imdb['Released_Year'].nunique()

100

In [12]:
# Count the number of movies in each "Released_Year"? 
imdb['Released_Year'].value_counts()

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1926     1
1936     1
1924     1
1921     1
PG       1
Name: count, Length: 100, dtype: int64

In [13]:
# In this dataset, there is a movie with an error in "Released_Year". (Hint: Released_Year should be a 4-digit integer.)
# Find this movie. 
imdb[imdb['Released_Year'].str.isdigit()==False]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [14]:
imdb['Released_Year'].unique()

array(['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010',
       '1999', '2001', '1966', '2002', '1990', '1980', '1975', '2020',
       '2019', '2014', '1998', '1997', '1995', '1991', '1977', '1962',
       '1954', '1946', '2011', '2006', '2000', '1988', '1985', '1968',
       '1960', '1942', '1936', '1931', '2018', '2017', '2016', '2012',
       '2009', '2007', '1984', '1981', '1979', '1971', '1963', '1964',
       '1950', '1940', '2013', '2005', '2004', '1992', '1987', '1986',
       '1983', '1976', '1973', '1965', '1959', '1958', '1952', '1948',
       '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
       '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951',
       '1949', '1939', '1937', '1934', '1928', '1926', '1920', '1970',
       '1969', '1956', '1947', '1945', '1930', '1938', '1935', '1933',
       '1932', '1922', '1943', 'PG'], dtype=object)

In [15]:
# Correct the values for the corresponding columns ("Release_Year" and "Certificate"). 
# You may want to look up this movie on www.imdb.com. 
# Hint: You can set value for a particular set by: loc[row_name, column_name] = new_value
imdb.loc[966,'Released_Year'] = 1995
imdb.loc[966,'Certificate'] = 'PG'
imdb.loc[966]

Poster_Link      https://m.media-amazon.com/images/M/MV5BNjEzYj...
Series_Title                                             Apollo 13
Released_Year                                                 1995
Certificate                                                     PG
Runtime                                                    140 min
Genre                                    Adventure, Drama, History
IMDB_Rating                                                    7.6
Overview         NASA must devise a strategy to return Apollo 1...
Meta_score                                                    77.0
Director                                                Ron Howard
Star1                                                    Tom Hanks
Star2                                                  Bill Paxton
Star3                                                  Kevin Bacon
Star4                                                  Gary Sinise
No_of_Votes                                                 269197
Gross                                                  173,837,933
Name: 966, dtype: object

In [16]:
# Change "Released_Year" from string to int
imdb['Released_Year'] = imdb['Released_Year'].apply(int)
imdb['Released_Year'].dtype

dtype('int64')

In [17]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.

imdb[(imdb.Released_Year>=2010) & (imdb.IMDB_Rating>=8.5)][['Series_Title','Released_Year','Certificate','IMDB_Rating']]

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [18]:
# Select all movies whose genres contain 'Animation'
imdb[imdb.Genre.str.contains('Animation')]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
23,https://m.media-amazon.com/images/M/MV5BMjlmZm...,Sen to Chihiro no kamikakushi,2001,U,125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,"10,055,859"
43,https://m.media-amazon.com/images/M/MV5BYTYxNG...,The Lion King,1994,U,88 min,"Animation, Adventure, Drama",8.5,Lion prince Simba and his father are targeted ...,88.0,Roger Allers,Rob Minkoff,Matthew Broderick,Jeremy Irons,James Earl Jones,942045,"422,783,777"
46,https://m.media-amazon.com/images/M/MV5BZmY2Nj...,Hotaru no haka,1988,U,89 min,"Animation, Drama, War",8.5,A young boy and his little sister struggle to ...,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
56,https://m.media-amazon.com/images/M/MV5BODRmZD...,Kimi no na wa.,2016,U,106 min,"Animation, Drama, Fantasy",8.4,Two strangers find themselves linked in a biza...,79.0,Makoto Shinkai,Ryûnosuke Kamiki,Mone Kamishiraishi,Ryô Narita,Aoi Yûki,194838,"5,017,246"
58,https://m.media-amazon.com/images/M/MV5BMjMwND...,Spider-Man: Into the Spider-Verse,2018,U,117 min,"Animation, Action, Adventure",8.4,Teen Miles Morales becomes the Spider-Man of h...,87.0,Bob Persichetti,Peter Ramsey,Rodney Rothman,Shameik Moore,Jake Johnson,375110,"190,241,310"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,https://m.media-amazon.com/images/M/MV5BODkxNG...,Mulan,1998,U,88 min,"Animation, Adventure, Family",7.6,"To save her father from death in the army, a y...",71.0,Tony Bancroft,Barry Cook,Ming-Na Wen,Eddie Murphy,BD Wong,256906,"120,620,254"
971,https://m.media-amazon.com/images/M/MV5BMTY5Nj...,Omohide poro poro,1991,U,118 min,"Animation, Drama, Romance",7.6,A twenty-seven-year-old office worker travels ...,90.0,Isao Takahata,Miki Imai,Toshirô Yanagiba,Yoko Honna,Mayumi Izuka,27071,"453,243"
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,"111,543,479"
986,https://m.media-amazon.com/images/M/MV5BMzZiOD...,Watership Down,1978,U,91 min,"Animation, Adventure, Drama",7.6,Hoping to escape destruction by human develope...,64.0,Martin Rosen,John Hubley,John Hurt,Richard Briers,Ralph Richardson,33656,NaN
992,https://m.media-amazon.com/images/M/MV5BMjAwMT...,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,Bagheera the Panther and Baloo the Bear have a...,65.0,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,"141,843,612"

In [19]:
# Create a new dataframe called "stars" including the following columns: 
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]
stars

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,1956,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,1953,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,1944,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,1935,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [20]:
# Create a new dataframe called "genres" including the following columns: 
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']]
genres

                 Series_Title  Released_Year                     Genre
0    The Shawshank Redemption           1994                     Drama
1               The Godfather           1972              Crime, Drama
2             The Dark Knight           2008      Action, Crime, Drama
3      The Godfather: Part II           1974              Crime, Drama
4                12 Angry Men           1957              Crime, Drama
..                        ...            ...                       ...
995    Breakfast at Tiffany's           1961    Comedy, Drama, Romance
996                     Giant           1956            Drama, Western
997     From Here to Eternity           1953       Drama, Romance, War
998                  Lifeboat           1944                Drama, War
999              The 39 Steps           1935  Crime, Mystery, Thriller

[1000 rows x 3 columns]

In [21]:
# Sorting:
# Sort dataframe genres in ascending order of "Released_Year"
genres.sort_values('Released_Year', ascending=True)

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
20                Soorarai Pottru           2020                         Drama
205                          Soul           2020  Animation, Adventure, Comedy
613                          Druk           2020                 Comedy, Drama
464                   Dil Bechara           2020        Comedy, Drama, Romance
612    The Trial of the Chicago 7           2020      Drama, History, Thriller

[1000 rows x 3 columns]

In [22]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
(
    imdb[(imdb.Released_Year>=2010) & (imdb.IMDB_Rating>=8.5)]
    [['Series_Title','Released_Year','Certificate','Gross']]
    .sort_values('Gross', ascending=False)
)

        Series_Title  Released_Year Certificate        Gross
19      Gisaengchung           2019           A   53,367,844
33             Joker           2019           A  335,451,311
8          Inception           2010          UA  292,576,195
21      Interstellar           2014          UA  188,020,017
35  The Intouchables           2011          UA   13,182,281
34          Whiplash           2014           A   13,092,000
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [23]:
# Does the sorting result looks right to you? What's the problem? 

# Answer: Gross is a string type.

In [24]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful: 
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe

imdb['Gross'] = imdb['Gross'].apply(str).str.replace(',','').apply(float)
imdb['Gross']

0       28341469.0
1      134966411.0
2      534858444.0
3       57300000.0
4        4360000.0
          ...
995            NaN
996            NaN
997     30500000.0
998            NaN
999            NaN
Name: Gross, Length: 1000, dtype: float64

In [25]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
(
    imdb[(imdb.Released_Year>=2010) & (imdb.IMDB_Rating>=8.5)]
    [['Series_Title','Released_Year','Certificate','Gross']]
    .sort_values('Gross', ascending=False)
)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [26]:
# Add a new column "Runtime_min" by removing the string ' min" in "Runtime"
# Set its data type as int

imdb['Runtime_min'] = imdb['Runtime'].str[:-4].astype(int)
imdb['Runtime_min']

0      142
1      175
2      152
3      202
4       96
      ...
995    115
996    201
997    118
998     97
999     86
Name: Runtime_min, Length: 1000, dtype: int32

In [29]:
# Add a new column "Age_Year" by expression: Current_Year - Released_Year
imdb['Age_Year'] = 2025 - imdb['Released_Year']
imdb[['Released_Year','Age_Year']]

     Released_Year  Age_Year
0             1994        31
1             1972        53
2             2008        17
3             1974        51
4             1957        68
..             ...       ...
995           1961        64
996           1956        69
997           1953        72
998           1944        81
999           1935        90

[1000 rows x 2 columns]

In [30]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc. 
imdb['Decade'] = imdb['Released_Year'] // 10 * 10
imdb['Decade']

0      1990
1      1970
2      2000
3      1970
4      1950
       ...
995    1960
996    1950
997    1950
998    1940
999    1930
Name: Decade, Length: 1000, dtype: int64

## Part 2: Data Summarization

In [ ]:
# Total "Gross" of all top 1000 movies
imdb['Gross'].sum()

In [ ]:
# Average "No_of_Votes" of all movies
imdb.No_of_Votes.mean()

In [ ]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
imdb.groupby('Decade').agg({'Series_Title':'count'}).sort_values('Series_Title',ascending=False)

In [ ]:
# Count movies by different director.
# Show the top 10 directors with the most movies in this list
(
    imdb
    .groupby('Director')
    .agg({'Series_Title':'count'})
    .sort_values('Series_Title',ascending=False)
    .head(10)
)

In [ ]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross. 
# Ranked in descending order of total gross
# Show the top 10 directors with the most gross
(imdb
 .groupby('Director')
 .agg({
     'Series_Title':'count',
     'IMDB_Rating': 'mean',
     'Gross': 'sum'
 })
 .sort_values('Gross',ascending=False)
 .head(10)
)

In [ ]:
# Group movies by decade and director 
# In each group (i.e., for each decade and each director), 
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count

(imdb
 .groupby(['Decade','Director'])
 .agg({
     'Series_Title':'count',
     'IMDB_Rating': 'mean'
 })
 .sort_values('Series_Title', ascending=False)
)

In [31]:
# Bonus Question 1: 
# Find the top 3 highest rated movies of each year since 2010. 
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking

imdb['rank_year'] = imdb.groupby(['Released_Year'])['IMDB_Rating'].rank(method='min',ascending=False)

(imdb[(imdb.Released_Year>=2010) & (imdb.rank_year<=3)]
 [['Released_Year','rank_year','Series_Title','IMDB_Rating']]
 .sort_values(['Released_Year','rank_year'],ascending=[False, True])
)

     Released_Year  rank_year                       Series_Title  IMDB_Rating
18            2020        1.0                           Hamilton          8.6
20            2020        1.0                    Soorarai Pottru          8.6
205           2020        3.0                               Soul          8.1
19            2019        1.0                       Gisaengchung          8.6
33            2019        2.0                              Joker          8.5
59            2019        3.0                  Avengers: Endgame          8.4
53            2018        1.0                         Capharnaüm          8.4
58            2018        1.0  Spider-Man: Into the Spider-Verse          8.4
60            2018        1.0             Avengers: Infinity War          8.4
54            2017        1.0          Ayla: The Daughter of War          8.4
55            2017        1.0                       Vikram Vedha          8.4
61            2017        1.0                               Coco          8.4
56            2016        1.0                     Kimi no na wa.          8.4
57            2016        1.0                             Dangal          8.4
196           2016        3.0                               Pink          8.1
197           2016        3.0                     Koe no katachi          8.1
198           2016        3.0                       Contratiempo          8.1
199           2016        3.0                          Ah-ga-ssi          8.1
212           2016        3.0                      Hacksaw Ridge          8.1
133           2015        1.0                             Talvar          8.2
136           2015        1.0                           Drishyam          8.2
203           2015        3.0                               Room          8.1
213           2015        3.0                         Inside Out          8.1
218           2015        3.0                          Spotlight          8.1
223           2015        3.0                 Mad Max: Fury Road          8.1
21            2014        1.0                       Interstellar          8.6
34            2014        2.0                           Whiplash          8.5
200           2014        3.0                              Mommy          8.1
201           2014        3.0                             Haider          8.1
204           2014        3.0                   Relatos salvajes          8.1
206           2014        3.0                         Kis Uykusu          8.1
207           2014        3.0                                 PK          8.1
209           2014        3.0           The Grand Budapest Hotel          8.1
210           2014        3.0                          Gone Girl          8.1
219           2014        3.0                    Song of the Sea          8.1
87            2013        1.0                           Drishyam          8.3
137           2013        2.0                              Queen          8.2
138           2013        2.0                        Mandariinid          8.2
139           2013        2.0                 Bhaag Milkha Bhaag          8.2
147           2013        2.0            The Wolf of Wall Street          8.2
62            2012        1.0                   Django Unchained          8.4
63            2012        1.0              The Dark Knight Rises          8.4
88            2012        3.0                             Jagten          8.3
35            2011        1.0                   The Intouchables          8.5
89            2011        2.0            Jodaeiye Nader az Simin          8.3
144           2011        3.0                            Warrior          8.2
8             2010        1.0                          Inception          8.8
90            2010        2.0                          Incendies          8.3
141           2010        3.0                              Udaan          8.2
145           2010        3.0                     Shutter Island          8.2
151           2010        3.0                        Toy Story 3          8.2

In [33]:
# Bonus Question 2: 
# Find all directors whose movies appeared in at least five different decades. 
# Your result should include: director, decade, and the number of movies in the decade.
df1 = imdb.groupby(['Director','Decade']).agg({'Series_Title':'count'}).reset_index()

df1.groupby(['Director']).filter(lambda x: x['Decade'].count()>=5)

             Director  Decade  Series_Title
247    Hayao Miyazaki    1970             1
248    Hayao Miyazaki    1980             4
249    Hayao Miyazaki    1990             2
250    Hayao Miyazaki    2000             3
251    Hayao Miyazaki    2010             1
424   Martin Scorsese    1970             1
425   Martin Scorsese    1980             3
426   Martin Scorsese    1990             2
427   Martin Scorsese    2000             1
428   Martin Scorsese    2010             3
644  Steven Spielberg    1970             2
645  Steven Spielberg    1980             5
646  Steven Spielberg    1990             3
647  Steven Spielberg    2000             2
648  Steven Spielberg    2010             1