## Case Study

The dataset "who.csv" contains tuberculosis (TB) cases broken down by year, country, age, gender, and diagnosis method. The data comes from the 2014 World Health Organization Global Tuberculosis Report, available at http://www.who.int/tb/country/data/download/en/.

In [1]:
import pandas as pd
import numpy as np

In [2]:
who = pd.read_csv('../data/who.csv', header=0)
who.head()

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,...,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
0,Afghanistan,AF,AFG,1980,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AF,AFG,1981,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AF,AFG,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,1983,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,1984,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
who.shape

(7240, 60)

In [4]:
who.columns

Index(['country', 'iso2', 'iso3', 'year', 'new_sp_m014', 'new_sp_m1524',
       'new_sp_m2534', 'new_sp_m3544', 'new_sp_m4554', 'new_sp_m5564',
       'new_sp_m65', 'new_sp_f014', 'new_sp_f1524', 'new_sp_f2534',
       'new_sp_f3544', 'new_sp_f4554', 'new_sp_f5564', 'new_sp_f65',
       'new_sn_m014', 'new_sn_m1524', 'new_sn_m2534', 'new_sn_m3544',
       'new_sn_m4554', 'new_sn_m5564', 'new_sn_m65', 'new_sn_f014',
       'new_sn_f1524', 'new_sn_f2534', 'new_sn_f3544', 'new_sn_f4554',
       'new_sn_f5564', 'new_sn_f65', 'new_ep_m014', 'new_ep_m1524',
       'new_ep_m2534', 'new_ep_m3544', 'new_ep_m4554', 'new_ep_m5564',
       'new_ep_m65', 'new_ep_f014', 'new_ep_f1524', 'new_ep_f2534',
       'new_ep_f3544', 'new_ep_f4554', 'new_ep_f5564', 'new_ep_f65',
       'newrel_m014', 'newrel_m1524', 'newrel_m2534', 'newrel_m3544',
       'newrel_m4554', 'newrel_m5564', 'newrel_m65', 'newrel_f014',
       'newrel_f1524', 'newrel_f2534', 'newrel_f3544', 'newrel_f4554',
       'newrel_f5564', 'newrel_f65'],
      dtype='object')

It is obvious that this dataset is not tidy. So let's tidy it up. 

The best place to start is almost always to gather together the columns that are not variables. Let’s have a look at what we’ve got:
- It looks like ``country``, ``iso2``, and ``iso3`` are three variables that redundantly specify the country.
- ``year`` is clearly also a variable.
- We don’t know what all the other columns are yet, but given the structure in the variable names (e.g. ``new_sp_m014``, ``new_ep_m014``, ``new_ep_f014``) these are likely to be values, not variables.

According to WHO's data dictionary: 
1. The first three letters of each column denote whether the column contains ``new`` or ``old`` cases of TB. In this dataset, each column contains ``new`` cases.
2. The next 2~3 letters describe the type of TB:
 - ``rel`` stands for cases of relapse
 - ``ep`` stands for cases of extrapulmonary TB
 - ``sn`` stands for cases of pulmonary TB that could not be diagnosed by a pulmonary smear (smear negative)
 - ``sp`` stands for cases of pulmonary TB that could be diagnosed by a pulmonary smear (smear positive)
3. The sixth letter gives the sex of TB patients. The dataset groups cases by males (``m``) and females (``f``).
4. The remaining numbers gives the age group. The dataset groups cases into seven age groups:
 - ``014`` = 0 – 14 years old
 - ``1524`` = 15 – 24 years old
 - ``2534`` = 25 – 34 years old
 - ``3544`` = 35 – 44 years old
 - ``4554`` = 45 – 54 years old
 - ``5564`` = 55 – 64 years old
 - ``65`` = 65 or older
 
Your final dataframe should contain the following columns: **country**, **year**, **cases**, **type**, **sex**, **age**

In [5]:
# Reshape the data frame. Shall we make it longer or wider? 
# If value_vars is not specified, melt() uses all columns that are not set as id_vars.
who1 = who.melt(id_vars=['country','iso2','iso3','year'], 
                var_name='key', value_name='cases')
who1

            country iso2 iso3  year          key  cases
0       Afghanistan   AF  AFG  1980  new_sp_m014    NaN
1       Afghanistan   AF  AFG  1981  new_sp_m014    NaN
2       Afghanistan   AF  AFG  1982  new_sp_m014    NaN
3       Afghanistan   AF  AFG  1983  new_sp_m014    NaN
4       Afghanistan   AF  AFG  1984  new_sp_m014    NaN
...             ...  ...  ...   ...          ...    ...
405435     Zimbabwe   ZW  ZWE  2009   newrel_f65    NaN
405436     Zimbabwe   ZW  ZWE  2010   newrel_f65    NaN
405437     Zimbabwe   ZW  ZWE  2011   newrel_f65    NaN
405438     Zimbabwe   ZW  ZWE  2012   newrel_f65    NaN
405439     Zimbabwe   ZW  ZWE  2013   newrel_f65  725.0

[405440 rows x 6 columns]

In [6]:
# Drop rows with missing values
who1 = who1.dropna(subset='cases')
who1

                          country iso2 iso3  year          key   cases
17                    Afghanistan   AF  AFG  1997  new_sp_m014     0.0
18                    Afghanistan   AF  AFG  1998  new_sp_m014    30.0
19                    Afghanistan   AF  AFG  1999  new_sp_m014     8.0
20                    Afghanistan   AF  AFG  2000  new_sp_m014    52.0
21                    Afghanistan   AF  AFG  2001  new_sp_m014   129.0
...                           ...  ...  ...   ...          ...     ...
405269                   Viet Nam   VN  VNM  2013   newrel_f65  3110.0
405303  Wallis and Futuna Islands   WF  WLF  2013   newrel_f65     2.0
405371                      Yemen   YE  YEM  2013   newrel_f65   360.0
405405                     Zambia   ZM  ZMB  2013   newrel_f65   669.0
405439                   Zimbabwe   ZW  ZWE  2013   newrel_f65   725.0

[76046 rows x 6 columns]

In [7]:
# Let's try to figure out the meaning of the new column: key
# Count the number of rows for each key value
who1['key'].value_counts()

new_sp_m4554    3223
new_sp_m3544    3219
new_sp_m5564    3218
new_sp_m65      3209
new_sp_m1524    3209
new_sp_m2534    3206
new_sp_f4554    3204
new_sp_f2534    3200
new_sp_f3544    3199
new_sp_f65      3197
new_sp_f5564    3195
new_sp_f1524    3194
new_sp_f014     3174
new_sp_m014     3173
new_sn_m014     1045
new_sn_f014     1040
new_ep_m014     1038
new_ep_f014     1032
new_sn_m1524    1030
new_sn_m4554    1027
new_ep_m1524    1026
new_sn_m3544    1025
new_ep_m3544    1024
new_sn_m2534    1022
new_sn_f1524    1022
new_ep_f3544    1021
new_ep_f2534    1021
new_ep_f1524    1021
new_sn_m5564    1021
new_ep_m2534    1020
new_ep_m4554    1020
new_sn_f3544    1020
new_sn_m65      1020
new_sn_f65      1019
new_sn_f4554    1018
new_ep_m65      1018
new_ep_f4554    1017
new_ep_f5564    1017
new_sn_f5564    1017
new_sn_f2534    1016
new_ep_m5564    1015
new_ep_f65      1014
newrel_f014      190
newrel_m014      190
newrel_m5564     185
newrel_f65       185
newrel_m3544     184
newrel_m4554     184
newrel_f1524     184
newrel_m2534     183
newrel_f3544     183
newrel_f4554     183
newrel_f5564     183
newrel_m65       182
newrel_m1524     182
newrel_f2534     182
Name: key, dtype: int64

In [8]:
# Since all cases in this dataset are new, not old. We do not need to deal with the first three letters too much.
# The second group should be "type" but the value 'rel' is a bit different from others
# To make things consistent, we add a '_' between 'new' and 'rel'.
who2 = who1.copy()
who2['key'] = who2['key'].str.replace('newrel','new_rel')
who2['key'].unique()

array(['new_sp_m014', 'new_sp_m1524', 'new_sp_m2534', 'new_sp_m3544',
       'new_sp_m4554', 'new_sp_m5564', 'new_sp_m65', 'new_sp_f014',
       'new_sp_f1524', 'new_sp_f2534', 'new_sp_f3544', 'new_sp_f4554',
       'new_sp_f5564', 'new_sp_f65', 'new_sn_m014', 'new_sn_m1524',
       'new_sn_m2534', 'new_sn_m3544', 'new_sn_m4554', 'new_sn_m5564',
       'new_sn_m65', 'new_sn_f014', 'new_sn_f1524', 'new_sn_f2534',
       'new_sn_f3544', 'new_sn_f4554', 'new_sn_f5564', 'new_sn_f65',
       'new_ep_m014', 'new_ep_m1524', 'new_ep_m2534', 'new_ep_m3544',
       'new_ep_m4554', 'new_ep_m5564', 'new_ep_m65', 'new_ep_f014',
       'new_ep_f1524', 'new_ep_f2534', 'new_ep_f3544', 'new_ep_f4554',
       'new_ep_f5564', 'new_ep_f65', 'new_rel_m014', 'new_rel_m1524',
       'new_rel_m2534', 'new_rel_m3544', 'new_rel_m4554', 'new_rel_m5564',
       'new_rel_m65', 'new_rel_f014', 'new_rel_f1524', 'new_rel_f2534',
       'new_rel_f3544', 'new_rel_f4554', 'new_rel_f5564', 'new_rel_f65'],
      dtype=object)

In [9]:
# Create three new columns by splitting the key column
who2[["new", "type", "sexage"]] = who2['key'].str.split("_", expand=True)
who2

,country,iso2,iso3,year,key,cases,new,type,sexage
17,Afghanistan,AF,AFG,1997,new_sp_m014,0.0,new,sp,m014
18,Afghanistan,AF,AFG,1998,new_sp_m014,30.0,new,sp,m014
19,Afghanistan,AF,AFG,1999,new_sp_m014,8.0,new,sp,m014
20,Afghanistan,AF,AFG,2000,new_sp_m014,52.0,new,sp,m014
21,Afghanistan,AF,AFG,2001,new_sp_m014,129.0,new,sp,m014
...,...,...,...,...,...,...,...,...,...
405269,Viet Nam,VN,VNM,2013,new_rel_f65,3110.0,new,rel,f65
405303,Wallis and Futuna Islands,WF,WLF,2013,new_rel_f65,2.0,new,rel,f65
405371,Yemen,YE,YEM,2013,new_rel_f65,360.0,new,rel,f65
405405,Zambia,ZM,ZMB,2013,new_rel_f65,669.0,new,rel,f65
405439,Zimbabwe,ZW,ZWE,2013,new_rel_f65,725.0,new,rel,f65

In [10]:
# Drop the redundant columns
who2.drop(columns=['iso2','iso3','key','new'], inplace=True)
who2

                          country  year   cases type sexage
17                    Afghanistan  1997     0.0   sp   m014
18                    Afghanistan  1998    30.0   sp   m014
19                    Afghanistan  1999     8.0   sp   m014
20                    Afghanistan  2000    52.0   sp   m014
21                    Afghanistan  2001   129.0   sp   m014
...                           ...   ...     ...  ...    ...
405269                   Viet Nam  2013  3110.0  rel    f65
405303  Wallis and Futuna Islands  2013     2.0  rel    f65
405371                      Yemen  2013   360.0  rel    f65
405405                     Zambia  2013   669.0  rel    f65
405439                   Zimbabwe  2013   725.0  rel    f65

[76046 rows x 5 columns]

In [11]:
# Separate sexage into sex and age by splitting after the first character
who2['sex'] = who2['sexage'].str[:1]
who2['age'] = who2['sexage'].str[1:]
who2

                          country  year   cases type sexage sex  age
17                    Afghanistan  1997     0.0   sp   m014   m  014
18                    Afghanistan  1998    30.0   sp   m014   m  014
19                    Afghanistan  1999     8.0   sp   m014   m  014
20                    Afghanistan  2000    52.0   sp   m014   m  014
21                    Afghanistan  2001   129.0   sp   m014   m  014
...                           ...   ...     ...  ...    ...  ..  ...
405269                   Viet Nam  2013  3110.0  rel    f65   f   65
405303  Wallis and Futuna Islands  2013     2.0  rel    f65   f   65
405371                      Yemen  2013   360.0  rel    f65   f   65
405405                     Zambia  2013   669.0  rel    f65   f   65
405439                   Zimbabwe  2013   725.0  rel    f65   f   65

[76046 rows x 7 columns]

In [12]:
who2.drop(columns='sexage', inplace=True)
who2

                          country  year   cases type sex  age
17                    Afghanistan  1997     0.0   sp   m  014
18                    Afghanistan  1998    30.0   sp   m  014
19                    Afghanistan  1999     8.0   sp   m  014
20                    Afghanistan  2000    52.0   sp   m  014
21                    Afghanistan  2001   129.0   sp   m  014
...                           ...   ...     ...  ...  ..  ...
405269                   Viet Nam  2013  3110.0  rel   f   65
405303  Wallis and Futuna Islands  2013     2.0  rel   f   65
405371                      Yemen  2013   360.0  rel   f   65
405405                     Zambia  2013   669.0  rel   f   65
405439                   Zimbabwe  2013   725.0  rel   f   65

[76046 rows x 6 columns]

In [13]:
who2 = who2.reset_index()
who2

        index                    country  year   cases type sex  age
0          17                Afghanistan  1997     0.0   sp   m  014
1          18                Afghanistan  1998    30.0   sp   m  014
2          19                Afghanistan  1999     8.0   sp   m  014
3          20                Afghanistan  2000    52.0   sp   m  014
4          21                Afghanistan  2001   129.0   sp   m  014
...       ...                        ...   ...     ...  ...  ..  ...
76041  405269                   Viet Nam  2013  3110.0  rel   f   65
76042  405303  Wallis and Futuna Islands  2013     2.0  rel   f   65
76043  405371                      Yemen  2013   360.0  rel   f   65
76044  405405                     Zambia  2013   669.0  rel   f   65
76045  405439                   Zimbabwe  2013   725.0  rel   f   65

[76046 rows x 7 columns]

In [14]:
who2.drop(columns='index', inplace=True)

In [15]:
who2

                         country  year   cases type sex  age
0                    Afghanistan  1997     0.0   sp   m  014
1                    Afghanistan  1998    30.0   sp   m  014
2                    Afghanistan  1999     8.0   sp   m  014
3                    Afghanistan  2000    52.0   sp   m  014
4                    Afghanistan  2001   129.0   sp   m  014
...                          ...   ...     ...  ...  ..  ...
76041                   Viet Nam  2013  3110.0  rel   f   65
76042  Wallis and Futuna Islands  2013     2.0  rel   f   65
76043                      Yemen  2013   360.0  rel   f   65
76044                     Zambia  2013   669.0  rel   f   65
76045                   Zimbabwe  2013   725.0  rel   f   65

[76046 rows x 6 columns]

In [16]:
# For each country, what is the total number of cases for male vs female
(
    who2
    .groupby(['country','sex'])
    .agg({'cases':'sum'})
    .reset_index()
    .pivot(index='country', columns='sex', values='cases')
    .reset_index()
)

sex                    country         f         m
0                  Afghanistan   93354.0   46871.0
1                      Albania    1830.0    3505.0
2                      Algeria   50522.0   77597.0
3               American Samoa      21.0      20.0
4                      Andorra      41.0      62.0
..                         ...       ...       ...
214  Wallis and Futuna Islands      20.0      21.0
215   West Bank and Gaza Strip     107.0     197.0
216                      Yemen   39901.0   44261.0
217                     Zambia  111026.0  152812.0
218                   Zimbabwe  172729.0  187686.0

[219 rows x 3 columns]